import mongoose, { Model, Schema } from "mongoose";

/**
 * One bounded, structured memory per completed room pitch
 * (plans/RAG_feature.md Phase 4). Generated by the `generate-room-memory`
 * worker job -- never stores the transcript, only a searchable summary plus
 * its embedding. `search_previous_pitch_memory` searches these, not
 * transcript sentences.
 */
const RoomMemorySchema = new Schema<RoomMemory>(
  {
    userId: { type: Schema.Types.ObjectId, ref: "User", required: true },
    roomId: { type: Schema.Types.ObjectId, ref: "PitchRoom", required: true },
    pitchId: { type: Schema.Types.ObjectId, ref: "Pitch", required: true },
    founderClaims: { type: [String], default: [] },
    weaknesses: { type: [String], default: [] },
    decisions: { type: [String], default: [] },
    newFacts: { type: [String], default: [] },
    recurringDifficulties: { type: [String], default: [] },
    summaryText: { type: String, required: true },
    embedding: { type: [Number], required: true },
    embeddingModel: { type: String, required: true },
    embeddingModelVersion: { type: String, required: true },
  },
  { timestamps: true }
);

// Unique on (roomId, pitchId) -- a retried generate-room-memory job (BullMQ
// jobId dedup already helps, but this is the authoritative guard) can never
// create a duplicate memory for the same pitch.
RoomMemorySchema.index({ roomId: 1, pitchId: 1 }, { unique: true });
RoomMemorySchema.index({ userId: 1, roomId: 1 });

const RoomMemoryModel: Model<RoomMemory> =
  mongoose.models.RoomMemory || mongoose.model<RoomMemory>("RoomMemory", RoomMemorySchema);

export default RoomMemoryModel;
